### ISSUE TITLE
PA_66: Digit on x-axis scale is not properly shown

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#297] opened 2015-07-31 12:21 UTC
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**OS/BROWSER:** Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html  2)	Bubble chart page will be loaded
3)	Note that the first digits written on the X-axis of the chart is truncated from left side.

**ACTUAL RESULTS:**
Digits are not properly shown to the user on X-axis on the chart. First digit is terminated form left side.

**EXPECTED RESULTS:**
All the digits on x-axis scale should be properly shown 

**SCREENSHOT:**
![vizabi_bubblechart_03](https://cloud.githubusercontent.com/assets/9950837/9007202/7ceb4306-37a8-11e5-9987-11c3aff5fc53.png)

**Comment by angieskazka** [comment] 2015-08-23 08:16
This issue can not be resolved by adjusting constants. It's a deeper problem concerning the interplay between label positioning engine axisWithLabelPicker.js and SVG within SVG axis containers needed for zoom feature of the bubble chart. Solution requires much understanding of all sides

**Comment by angieskazka** [comment] 2015-08-23 11:25
Duplicate of #103

**Closed by angieskazka** 2015-08-23 11:25 UTC
Labels: bubble-chart, bug
