### ISSUE TITLE
BLC_15: Menus on bubble chart are not localized under language PT

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#220] opened 2015-07-10 12:27 UTC
SEVERITY: Major

MODULE: Bubble Chart

OS/BROWSER: Windows 7/Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Set Lang: button of interaction button  
4)	Note that some of the menus are not localized 

ACTUAL RESULTS:
Some menus of bubble chart are not localized in setting language as PT

EXPECTED RESULTS: 
All menus should be localized according to selected language  

SCREENSHOT:
![vizabi_bubblechart_23](https://cloud.githubusercontent.com/assets/1772649/8618544/e2e8d6fe-2728-11e5-80a6-d6dec67f243d.png)

**Comment by IncoCode** [comment] 2015-08-07 10:56
Can't reproduce this issue on `develop` branch.

**Comment by k6Labz** [comment] 2015-08-13 07:15
It might be fixed, also can't be reproducible here on my side as checked on develop branch

**Comment by angieskazka** [comment] 2015-08-23 12:20
yes, it was fixed in v0.6

**Closed by angieskazka** 2015-08-23 12:20 UTC
Labels: bubble-chart, bug
