### ISSUE TITLE
Searchbox positioning in "show" menu. //Pop up is truncated on landscape  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1425] opened 2016-03-08 11:30 UTC
**SEVERITY:**  Major

**MODULE:**  Mountain chart

**Platform:**  iPhone-4G(iOS 7.1.2)/ Safari 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/mountain 
2)	Mountain Chart will be loaded.
3)	Change the orientation of the device to landscape
4)	Ta “Options” icon
5)	Tap “Show” 
6)	Note that pop up is truncated from bottom

**ACTUAL RESULTS:**
Pop up is truncated on landscape  

**EXPECTED RESULTS:**
Pop up should not be truncated 

**SCREENSHOT:**

![v0 12 8_15](https://cloud.githubusercontent.com/assets/9950837/13600523/0a717ee8-e54b-11e5-915a-45ab5c7c2bfa.PNG)

**Comment by angieskazka** [comment] 2016-03-08 14:10
Truncated popup is a duplicate of #1379 
But see also "search" on a dialog. Let's make it look like on "find" dialog

![image](https://cloud.githubusercontent.com/assets/3648190/13603764/cbc20fba-e53f-11e5-9b82-f7814763932c.png)

**Closed** 2016-03-09 09:14 UTC
