### ISSUE TITLE
Color - don't save the changes in the URL

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/vizabi#1302] opened 2016-02-01 08:51 UTC
## Description
don't save the changes in the URL at the change color

<b>SEVERITY:</b> Major

<b>MODULE:</b> 
• Bubble chart
• Bubble Map Chart
• Mountain Chart

<b>Platform:</b> mac os x 10.10 / Chrome 47.0

<b>RELEASE:</b> v0.12.5

<b>STEPS TO REPRODUCE: </b>
1) Navigate to the URL : https://tools-dev.gapminderdev.org/tools/bubbles
2) Click on color -> constant
     - for all menu color -> all items 
3) Open color palette and change color
4) Refresh page 

<b>ACTUAL RESULTS:</b>
After reloading the page - chart returned to the default color

**Comment by angieskazka** [comment] 2016-02-01 09:04
closing as duplicate of #1288

**Closed by angieskazka** 2016-02-01 09:04 UTC
