### ISSUE TITLE
Changes with "Follow bubbles with zoom"

### ISSUE THREAD

**Issue by valorkin** [Gapminder/vizabi#1286] opened 2016-01-27 05:44 UTC
# Description 
On clicking the checkbox of "Follow bubbles with zoom", changes takes effect on Bubbles immediately

# Actual result 
**SUMMARY:**  Axis value is truncated

**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:**  Windows 7 / Chrome 47.0 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Click “Options”
4)	Click “X and Y”
5)	Click check box of “Follow Bubble with zoom”
6)	Note that Y Axis value is truncated

**ACTUAL RESULTS:**
Y Axis value is truncated by clicking check box of “Follow Bubble with zoom”

**EXPECTED RESULTS:**
Axis value should not truncate in any case

# Other information 
Reported by: Abid Ali 

Test case number: TC39 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/189933?tab=2&run_section_id=162894&executed_case_id=9210273#executed_case_9210273](https://valorsoftware.testlodge.com/projects/15827/runs/189933?tab=2&run_section_id=162894&executed_case_id=9210273#executed_case_9210273)

**Comment by angieskazka** [comment] 2016-01-27 19:56
closing as duplicate of #103

**Closed by angieskazka** 2016-01-27 19:56 UTC
Labels: type: bug
