### ISSUE TITLE
Tools_v0.8.6 _22: Small pop up screen is disappeared automatically

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#902] opened 2015-11-10 11:53 UTC
**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/mountain 
2)	Tools page is loaded.
3)	Click “Stack” icon available on right bottom 
4)	Note that the small pop up screen is shown for a while and disappeared without any action

**ACTUAL RESULTS:**
By clicking “Stack” small pop up screen is shown for a while and disappeared without any action 

**EXPECTED RESULTS:** 
Small pop up screen should be displayed properly by clicking “Stack”

**SCREENSHOT:**

![tools_v0 8 6 _22](https://cloud.githubusercontent.com/assets/9950837/11061820/83c574d0-87cb-11e5-8882-9a1aa1a91fe7.png)

**Comment by arthurcamara1** [comment] 2015-11-10 13:46
There's certainly a bug there but I couldn't reproduce the same way

Stack is on the side for me

![image](https://cloud.githubusercontent.com/assets/3584238/11063896/d2f01a7c-87b9-11e5-86b1-a16166b5b5e8.png)

**Comment by angieskazka** [comment] 2015-11-12 00:06
this is a duplicate of #899. @rlage should be on it

**Comment by angieskazka** [comment] 2015-11-12 00:07
button "stack" should be hidden because "stack" dialog is in side bar

**Comment by arthurcamara1** [comment] 2015-11-12 09:49
@angieskazka though it shouldn't be :P I guess it should be in more-options only.

Close if duplicate?

**Closed** 2015-11-12 15:07 UTC
Labels: comp: buttons-controls-dialogs, comp: mountain-chart, dec 23 release, effort1: easy (hour), P2: required, type: bug
