### ISSUE TITLE
Dataset: Strange color of US trail-connector line ("usa" is in "america", not "americas")

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1507] opened 2016-03-16 18:25 UTC
steps to reproduce on develop

1. connect to the new data from WS
2. select UR
3. create trail
4. Zoom in to see the effect

![image](https://cloud.githubusercontent.com/assets/3648190/13832505/166b639c-ebdd-11e5-8318-99cc31717abe.png)

**Comment by angieskazka** [comment] 2016-03-19 23:13
Detective work:
this is because of a typo in a dataset: usa is in region america. should be in region 'americas', as all other american countries

![image](https://cloud.githubusercontent.com/assets/3648190/13901800/dd37ae82-ee2f-11e5-835f-5440bbdcfefe.png)

![image](https://cloud.githubusercontent.com/assets/3648190/13901795/bb8c0076-ee2f-11e5-96f4-fb081bca69a2.png)

the root cause in in Semio's dataset 
https://github.com/semio/ddf--gapminder_world/blob/master/output/ddf--entities--geo--country.csv

Let's bring GW "america" in consistency with SG (or SG in consistency with GW)

**Comment by jheeffer** [comment] 2016-03-21 12:41
No typo in dataset. This is how it is in GW. So either we change it in GW or in transforming to DDF. 
In the end Vizabi should not have these things hard coded. Now it does so we have to choose one.

**Comment by jheeffer** [comment] 2016-03-21 22:36
I'm going to merge geo.region entity set to GW data. That way it has both the right 'americas' and the south sudan and some other will belong to the regions where we had them in SG.

**Comment by angieskazka** [comment] 2016-03-22 00:56
resolved in dev now

**Closed by angieskazka** 2016-03-22 00:56 UTC
Labels: Gapminder World release
