### ISSUE TITLE
url link fails: axis min max not the same

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1236] opened 2016-01-12 13:02 UTC
To reproduce:
1. Go here:http://www.gapminder.org/tools/bubbles
2. Change y-axis indicator to Life expectancy
![image](https://cloud.githubusercontent.com/assets/496398/12264137/ce49afe0-b934-11e5-91ab-bf3c72c89368.png)

3. Copy url
4. Paste url into new browser tab
5. Compare the Y-axis of  the copied chart (step 2 above) and the pasted chart here: Y-axis min is different after pasting.

![image](https://cloud.githubusercontent.com/assets/496398/12264154/f7d7c2f2-b934-11e5-9131-c4d7819b611f.png)

**Comment by k6Labz** [comment] 2016-01-13 04:47
**SUMMARY:** URL link fail: Number of bubbles are not same

**SEVERITY:** Major

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0 

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2)	Tools page is loaded.
3)	Click Size. Small pop up screen is displayed.
4)	Click drop down and change the option “Population” to “GDP per capita”
5)	Note the bubbles (Screenshot 1)
6)	Copy the URL and paste in another tab
7)	Note that number of bubbles increased and are not same (Screenshot 2)

**ACTUAL RESULTS:**
Number of bubbles is not same after some changing and refreshing the page

**EXPECTED RESULTS:** 
On the same URL link the whole page should remain same even after refreshing it

**SCREENSHOT:**

**Screenshot 1:**
![v0 12 0_19 1](https://cloud.githubusercontent.com/assets/9950837/12285309/a2a597d6-b9da-11e5-91dd-e4c5f82f222c.png)


**Screenshot 2:**
![v0 12 0_19 2](https://cloud.githubusercontent.com/assets/9950837/12285310/a2a6368c-b9da-11e5-88d8-7e534e6ea79f.png)

**Comment by angieskazka** [comment] 2016-01-20 10:44
this happens because metadata in production is missing `domain` field for lex indicator
the chart tries to figure out the domain itself during splash load and it end up being only for 2015
It's already fixed in develop and stage

**Closed** 2016-01-20 10:45 UTC
Labels: type: enhancement
