### ISSUE TITLE
Y axis values are disturbed 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1628] opened 2016-04-07 09:58 UTC
**SEVERITY:**  Minor

**MODULE:**   Bubble chart

**Platform:** Windows 7 / Firefox 44.0

**RELEASE:** v0.13.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Map Chart will be loaded.
3)	Select USA and China
4)	Click play and drag the slider to the end(2015)
5)	Trails of selected bubbles will be available
6)	Click Options
7)	Click X and Y
8)	Click ‘Follow bubbles with zoom’
9)	Observe the y axis values

**ACTUAL RESULTS:**
Y axis values are disturbed when we select ‘Follow bubbles with zoom’ from X and Y axis after making trails of any country

**EXPECTED RESULTS:**
Y axis values should not be disturbed

**SCREENSHOT:**

![v0 13 6_02](https://cloud.githubusercontent.com/assets/9950837/14347591/57a9af62-fcd1-11e5-9979-91fd566da62c.png)

**Comment by angieskazka** [comment] 2016-04-11 21:21
duplicate of #1556, it's the same problem

**Closed by angieskazka** 2016-04-11 21:21 UTC
Labels: type: duplicate
