### ISSUE TITLE
Mountains are not shown for 'show'-selection

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#941] opened 2015-11-13 07:24 UTC
This issue only exists on the tools-page, both stage and dev. Not on the preview pages.

1. Go to http://stage-tools.gapminderdev.org/tools/mountain
2. Click show-button
3. Click any country
4. See that there is no mountain chart and povertyline is NaN %

This might point to a data error?

![image](https://cloud.githubusercontent.com/assets/1596071/11140914/2df0564e-89e0-11e5-98e4-2754eeb63f46.png)

**Comment by jheeffer** [comment] 2015-11-13 07:59
Duplicate of #802

**Comment by angieskazka** [comment] 2015-11-13 10:52
closing as duplicate of #802

**Comment by angieskazka** [comment] 2015-11-13 10:53
or actually let it stay open

**Comment by arthurcamara1** [comment] 2015-11-13 10:55
Just so you all remember, last time the issue was uppercase rather than lowercase ids

**Comment by arthurcamara1** [comment] 2015-11-13 10:57
Fixed already? :smile:

**Comment by angieskazka** [comment] 2015-11-13 10:58
@arthurcamara1 the bud is in waffle server
`"path": "//stage-ws.gapminderdev.org/api/graphs/stats/vizabi-tools",` -- works
`"path": "//waffles.gapminderdev.org/api/graphs/stats/vizabi-tools",` -- doesn't

**Comment by angieskazka** [comment] 2015-11-13 10:59
this is why prod works. because tools page stage points to ws prod
and tools page prod points to ws stage

**Comment by arthurcamara1** [comment] 2015-11-13 11:00
Yes @angieskazka , just checked now that this works:
http://stage-tools.gapminderdev.org/tools/mountain#_entities_show_geo@=ARG;;;&marker_axis%2F_y_min:0&max:2568192312.136342&fakeMin:0&fakeMax:2568192312.136342;&axis%2F_x_fakeMin:0.11&fakeMax:500;&color_palette_asi=%23FF5872&eur=%23FFE700&ame=%237FEB00&afr=%2300D5E9&%2F_default=%23ffb600

(I manually modified the url to have **ARG** instead of **arg**)

**Comment by angieskazka** [comment] 2015-11-13 13:54
@valorkin fixed this by updating WS stage

**Comment by k6Labz** [comment] 2016-01-07 04:41
@angieskazka 
This bug is reproduced again.

**Testing Environment:** http://stage-tools.gapminderdev.org/tools/mountain (Yule Goat) 

**Platform:** Windows 7 / 47.0

**Comment by angieskazka** [comment] 2016-01-13 12:04
comment: show list is not aware of the countries that are missing data

**Comment by angieskazka** [comment] 2016-01-21 09:40
the bug #1203 is the same. closing this as a duplicate

**Closed by angieskazka** 2016-01-21 09:40 UTC
Labels: comp: mountain-chart, dec 23 release, effort1: easy (hour), P1: urgent, type: bug
