### ISSUE TITLE
v0.8.6_16: Play icon is not working by changing the color option to “Region”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#884] opened 2015-11-06 12:33 UTC
**SEVERITY:**  Critical

**MODULE:**  Pop by age Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/popbyage.html
2)	Pop by age Chart will be loaded.
3)	Click “Full” button under RESPONSIVENESS
4)	Drag the slider ball to the star and click play
5)	While playing click color options
6)	Click dropdown and select “Region”
7)	Click pause
8)	Note that pause/play icon is not working
9)	Also note that after selecting “Region” the small colored ball is not gone and there is no map for region

**ACTUAL RESULTS:**
After selecting “Region” , the small colored ball is not gone and there is no map for region. And pause/play button is not working when we change the color option to “Region” while playing

**EXPECTED RESULTS:**
Play/pause icon should work in any case and map should be there after selecting “Region” from options

**SCREENSHOT:**

![v0 8 6_16](https://cloud.githubusercontent.com/assets/9950837/10997148/7da0c3f6-84ac-11e5-9c6c-a9195a04c78c.png)

**Comment by jheeffer** [comment] 2015-11-09 18:11
Create usa-geo-properties.csv file

**Comment by sergey-filipenko** [comment] 2015-11-10 12:02
duplicate of https://github.com/Gapminder/vizabi/issues/832

**Comment by sergey-filipenko** [comment] 2015-11-10 13:46
related  https://github.com/Gapminder/vizabi/issues/834

**Comment by jheeffer** [comment] 2015-11-10 14:11
closed by https://github.com/Gapminder/vizabi/commit/aed7c868f5c4d9f0287a1b9fa3fc570597662dea

**Closed by jheeffer** 2015-11-10 14:11 UTC
Labels: comp: popbyage-chart, effort1: easy (hour), P2: required, type: bug
