### ISSUE TITLE
v0.9.0_06: Color scale is missing for “Geo name”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1040] opened 2015-11-27 06:28 UTC
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Select Bubble map chart
4)	Click Color dropdown on right top
5)	Click “Properties” and select “Geo name”
6)	Note that color scale is missing for “Geo name” on right top

**ACTUAL RESULTS:**
Color scale is missing for “Geo name”

**EXPECTED RESULTS:** 
Color scale should be available for “Geo name”

**SCREENSHOT:**

![v0 9 0_06](https://cloud.githubusercontent.com/assets/9950837/11435239/f5a1a11a-94f9-11e5-8ed2-7e429445a5c3.png)

**Comment by angieskazka** [comment] 2015-11-27 19:25
duplicate of #1009

**Closed by angieskazka** 2015-11-27 19:25 UTC
Labels: comp: bubblemap, type: bug
