### ISSUE TITLE
Changes with "Follow bubbles with zoom"

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1356] opened 2016-02-12 05:09 UTC
# Description 
On clicking the checkbox of "Follow bubbles with zoom", changes takes effect on Bubbles immediately

# Actual result 
**SUMMARY:**  X axis value is truncated by clicking checkbox of "Follow bubbles with zoom"

**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:** 
* Windows 7 / Chrome 47.0 
* MAC / Safari 9.0
* iPad Air 2 iOS(9.2.1) / Safari 

**RELEASE:** v0.12.6
**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Drag the slider ball to year 1931
4)	Click options icon
5)	Click X and Y option
6)	Click checkbox of “Follow bubbles with zoom”
7)	Note that X axis value is truncated by clicking checkbox of “Follow bubbles with zoom”
8)     To reproduce this issue on iPad Air 2, drag the slider ball to year 1948.  

**ACTUAL RESULTS:**
X axis value is truncated by clicking checkbox of “Follow bubbles with zoom” at year 1930 to 1932

**EXPECTED RESULTS:**
X axis value should not be truncated by clicking checkbox of “Follow bubbles with zoom”

# Other information 
Reported by: Abid Ali 

Test configuration: Chrome, Desktop PC 

Test case number: TC39 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/192798?tab=2&run_section_id=168613&executed_case_id=9332093#executed_case_9332093](https://valorsoftware.testlodge.com/projects/15827/runs/192798?tab=2&run_section_id=168613&executed_case_id=9332093#executed_case_9332093)

**SCREENSHOT:**

![v0 12 6_03](https://cloud.githubusercontent.com/assets/9950837/12999430/d2f939f8-d170-11e5-9d61-92ae4f89de27.png)

**Comment by angieskazka** [comment] 2016-02-13 00:14
closing as a duplicate of #103

**Closed by angieskazka** 2016-02-13 00:14 UTC
Labels: type: bug
