### ISSUE TITLE
label leash not showing when short distance. 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1508] opened 2016-03-16 18:28 UTC
![image](https://cloud.githubusercontent.com/assets/496398/13824175/3b358b10-ebad-11e5-90d6-c49782c243de.png)

Always show leash between bubble and label

**Comment by angieskazka** [comment] 2016-03-16 19:23
duplicate of #1440

**Closed by angieskazka** 2016-03-16 19:23 UTC
Labels: Gapminder World release
