### ISSUE TITLE
v0.9.2_11: Regions are not arranged according to manual sorting

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1153] opened 2015-12-18 05:33 UTC
**Summary:**
**1)** Regions are not arranged according to manual sorting
**2)** No values for poverty line

**SEVERITY:** Major

**MODULE:** Tool Page

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/mountain 
2)	Tools page is loaded.
3)	Click “Stack”, small pop up screen is displayed
4)	Click “Regions” in the first line
~~5)	Change arrangement of regions under manual sorting of groups~~
6)	Note that regions are not arranged according to manual sorting and there is no value for poverty line 

**ACTUAL RESULTS:**
Regions are not arranged according to manual sorting and there is no value for poverty line 

**EXPECTED RESULTS:** 
Regions should be arranged according to manual sorting and value for poverty line should be there

**SCREENSHOT:**

![v0 9 2_11](https://cloud.githubusercontent.com/assets/9950837/11890103/9cce9f78-a572-11e5-8b10-f8b3e0e52ed7.png)

**Comment by angieskazka** [comment] 2015-12-23 19:35
couldn't reproduce, need retest

**Comment by k6Labz** [comment] 2015-12-28 04:52
@angieskazka 
The following issue can be reproduced on Windows 7 / Chrome 47.0.

**Screenshot:**

![comment](https://cloud.githubusercontent.com/assets/9950837/12014182/a8933e12-ad48-11e5-8f43-e92c8032be7f.png)

**Comment by angieskazka** [comment] 2015-12-28 20:35
after you change Stack radio button, the whole thing is broken already (because #1154) and you can't consider this a clean experiment

**Comment by angieskazka** [comment] 2016-01-04 20:12
#1154 is now fixed and so should be this one too

**Closed** 2016-01-04 20:15 UTC
Labels: comp: mountain-chart, dec 23 release, type: bug
