### ISSUE TITLE
v0.9.0_05: Bubbles are truncated by increasing bubble size

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1039] opened 2015-11-27 06:27 UTC
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Select Bubble map chart
4)	Click “Size”
5)	Increase bubble size to the maximum
6)	Note that bubbles are truncated by increasing bubble size

**ACTUAL RESULTS:**
Bubbles are truncated by increasing bubble size 

**EXPECTED RESULTS:** 
Bubbles should not truncate by increasing bubble size 

**SCREENSHOT:**

![v0 9 0_05](https://cloud.githubusercontent.com/assets/9950837/11435228/cf90a46c-94f9-11e5-891c-b5af8d0168f9.png)

**Comment by angieskazka** [comment] 2015-11-27 19:26
duplicate of #1020

**Closed by angieskazka** 2015-11-27 19:26 UTC
Labels: comp: bubblemap, type: bug
