### ISSUE TITLE
Tools_v0.8.1 _52 : Cross button is not center aligned

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#670] opened 2015-10-14 11:13 UTC
**SEVERITY:** minor

**MODULE:** Tools page (Bubble Chart)

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click “Data Doubts”
4)	Note that the cross button on pop up screen is not center aligned

**ACTUAL RESULTS:**
The cross button on pop up screen of data doubts is not center aligned

**EXPECTED RESULTS:** 
The cross button should be center aligned

**SCREENSHOT:**

![tools_v0 8 1 _52](https://cloud.githubusercontent.com/assets/9950837/10482045/7a9812b6-728e-11e5-9054-c618d23d9360.PNG)

**Comment by angieskazka** [comment] 2015-10-15 17:45
duplicate of #611 Cross symbol is not center aligned. fixed in v0.8.3

**Closed by angieskazka** 2015-10-15 17:45 UTC
Labels: enhancement
