### ISSUE TITLE
BLC_01: Same year is shown on different position on slide bar in sliding the Slider manually 

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#206] opened 2015-07-10 10:28 UTC
SEVERITY: Minor

MODULES: Bubble Chart, Bar Chart, Line Chart

OS/BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html
2) Bubble chart page will be loaded
3) Drag & drop the slider to a particular position i.e. 1990
4) Click on Slider where it is dropped
5) Note that Slider will move one step farther 
6) Click & hold on Slider’s new position, where it is moved
7) Note that Slider new position also shows the same year i.e. 1990

ACTUAL RESULTS:
Same year is shown in different position on sliding the Slider on slide bar

EXPECTED RESULTS: 
Same year should not be displayed on different position as other position correspond to another year on Slide bar, slider should not move ahead

SCREENSHOTS:
![vizabi_bubblechart_01a](https://cloud.githubusercontent.com/assets/1772649/8616900/48c23e5e-2718-11e5-9be4-ba415f55084d.png)
![vizabi_bubblechart_01b](https://cloud.githubusercontent.com/assets/1772649/8616901/48ca8d7a-2718-11e5-97d4-0f522fe590be.png)

![vizabi_barchart_01](https://cloud.githubusercontent.com/assets/1772649/8673161/c51355dc-2a4d-11e5-89f0-7fe0c89845f7.png)
![vizabi_barchart_01b](https://cloud.githubusercontent.com/assets/1772649/8673182/e44fbd28-2a4d-11e5-915d-6ce2c7f7b53b.png)

![vizabi_linechart_01](https://cloud.githubusercontent.com/assets/1772649/8697609/e4b68c16-2b0f-11e5-9e3a-dc750a36eda2.png)
![vizabi_linechart_01b](https://cloud.githubusercontent.com/assets/1772649/8697611/e54f2264-2b0f-11e5-99cb-37b208d7cc6e.png)

**Comment by arthurcamara1** [comment] 2015-08-23 20:33
Not a bug, part of the requirement.
Fixed with dcc0da96759532103c595aac99b001230d1c6d8b

**Closed by arthurcamara1** 2015-08-23 20:33 UTC
Labels: bar-chart, bubble-chart, bug, line-chart
