### ISSUE TITLE
wrong page title on example page

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#83] opened 2015-03-12 15:37 UTC
![image](https://cloud.githubusercontent.com/assets/496398/6621297/1d873c80-c8d6-11e4-83e4-f61cfd495add.png)

**Comment by angieskazka** [comment] 2015-03-12 21:26
@olarosling Do you mean "Line chart title"? Do we need any title there at all? It would look like a duplicate of the line below (Y axis title)

**Comment by arthurcamara1** [comment] 2015-03-12 23:59
I think it's OK here. This title comes from the embedding page... The GO
page will set this title

On Thu, Mar 12, 2015 at 10:26 PM, Angie the Fairytale <
notifications@github.com> wrote:

> @olarosling <https://github.com/olarosling> Do you mean "Line chart
> title"? Do we need any title there at all? It would look like a duplicate
> of the line below (Y axis title)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/83#issuecomment-78626056>.
>



-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org

**Comment by angieskazka** [comment] 2015-03-16 18:32
@arthurcamara1 do we close it then?

**Comment by angieskazka** [comment] 2015-03-19 21:46
We removed title for now all together. Title within the component does the thing now

**Closed** 2015-03-19 21:46 UTC
