### ISSUE TITLE
Scrollable dialogs should include a scrollbar

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#727] opened 2015-10-20 15:14 UTC
Right now, there's no visual cue that the div is scrollable.

![image](https://cloud.githubusercontent.com/assets/3584238/10611777/ebd77c14-774d-11e5-94b3-dc143a9634eb.png)

We would like to have a scrollbar that looks like this:

[TO BE EDITED]

**Comment by angieskazka** [comment] 2015-10-20 16:06
duplicate of #640

**Closed** 2015-10-20 16:41 UTC
Labels: buttons-controls-dialogs, duplicate, enhancement
