### ISSUE TITLE
Tools_v0.8.4 _26: A large space comes by expanding the screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#803] opened 2015-10-29 11:13 UTC
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Click the “Expand” button
4)	Note that there comes a large space on right side of the chart by expanding screen

**ACTUAL RESULTS:**
There comes a large space on right side of the chart by expanding screen

**EXPECTED RESULTS:** 
There should be any extra space by expanding screen.

**SCREENSHOT:**

![tools_v0 8 4 _26](https://cloud.githubusercontent.com/assets/9950837/10816863/e28b552a-7e57-11e5-80c1-db6149b388aa.png)

**Comment by angieskazka** [comment] 2015-11-04 22:59
this is a duplicate of #604 and is done in 0.8.6.

**Closed by angieskazka** 2015-11-04 22:59 UTC
Labels: enhancement
