### ISSUE TITLE
v0.8.6_24: Data doubt text is not localised

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#909] opened 2015-11-11 09:39 UTC
**SEVERITY:**  Minor

**MODULE:**  Mountain Chart.

**Platform:**
*  Windows 7 / Chrome 48.0
* Windows 7 / Firefox  43.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Click switch language button available on the right panel
~~~4) Note that the word ‘DATA’ is not localized to ‘uppgifter’~~~
4)  Click "Data tvivel", see the text in English

**ACTUAL RESULTS:**
By switching language the text is not localised

**EXPECTED RESULTS:**
By switching language the text should be localised

**SCREENSHOT:**

![image](https://cloud.githubusercontent.com/assets/3648190/11088842/99301c90-8865-11e5-9608-b3347a2b409a.png)

**Comment by angieskazka** [comment] 2015-12-01 16:33
duplicate of #772

**Closed by angieskazka** 2015-12-01 16:33 UTC
Labels: effort1: easy (hour), type: enhancement
