### ISSUE TITLE
Y-axis values are disturbed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1783] opened 2016-05-30 07:48 UTC
**SEVERITY:**  Minor

**MODULE:**   Bubble chart

**Platform:**
*   Windows 7 / Chrome 52.0
*    Windows 7 / Firefox 42.0

**RELEASE:** v0.13.11
**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Chart will be loaded.
3)	Click on zoom in and then click on bubbles once
4)	Click on zoom out and click again on bubbles
5)	Note that y-axis values are disturbed

**ACTUAL RESULTS:**
y-axis values get disturbed after changing zoom in to zoom out

**EXPECTED RESULTS:**
Axis values should be visible properly

**SCREENSHOT:** 

![v0 13 11_ 06](https://cloud.githubusercontent.com/assets/9950837/15643074/bd71b594-2664-11e6-8c06-34b58530ccc3.png)

**Comment by angieskazka** [comment] 2016-05-30 08:27
duplicate of #1556

**Closed by angieskazka** 2016-05-30 08:27 UTC
Labels: type: duplicate
