### ISSUE TITLE
y-axin min is masked

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#353] opened 2015-08-20 11:29 UTC
![image](https://cloud.githubusercontent.com/assets/496398/9382256/631ff3c6-473f-11e5-9a7c-3e5f9a704729.png)
http://bit.ly/1Nxezo2

**Comment by angieskazka** [comment] 2015-08-23 08:15
This issue can not be resolved by adjusting constants. It's a deeper problem concerning the interplay between label positioning engine axisWithLabelPicker.js and SVG within SVG axis containers needed for zoom feature of the bubble chart. Solution requires much understanding of all sides

**Comment by angieskazka** [comment] 2015-08-23 11:24
Duplicate of #103

**Closed by angieskazka** 2015-08-23 11:24 UTC
Labels: bubble-chart
