### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1334] opened 2016-02-11 05:16 UTC
# Description 
If you resize the window, the picture is not messed up, but adapts nicely.

# Actual result

**SUMMARY:**  Expand button is truncated on resizing the window

**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:**  MAC / Safari 9

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Resize the window
4)	Note that expand button is truncated on resizing the window

**ACTUAL RESULTS:**
Expand button is truncated on resizing the window

**EXPECTED RESULTS:**
No button should be truncated in any case

# Other information 
Reported by: Abid Ali 

Test configuration: Safari 9, MAC 

Test case number: TC02 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/192615?tab=2&run_section_id=168043&executed_case_id=9321239#executed_case_9321239](https://valorsoftware.testlodge.com/projects/15827/runs/192615?tab=2&run_section_id=168043&executed_case_id=9321239#executed_case_9321239)

**Comment by k6Labz** [comment] 2016-02-11 07:15
Closing as duplicate of #1333

**Closed by k6Labz** 2016-02-11 07:15 UTC
Labels: type: bug
