### ISSUE TITLE
v0.9.0_04: Tooltip lines are missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1038] opened 2015-11-27 06:26 UTC
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Select Bubble map chart
4)	Select any country. For example we select China, United Sates, Russia and Nigeria.
5)	Click Play and let the slider ball reach the end
6)	Click Play again 
7)	Note that tooltip lines for selected countries are missing

**ACTUAL RESULTS:**
Tooltip lines for selected countries are missing 

**EXPECTED RESULTS:** 
Tooltip lines should be available from bubble to tooltip for selected countries

**SCREENSHOT:**

![v0 9 0_04](https://cloud.githubusercontent.com/assets/9950837/11435218/af92daea-94f9-11e5-8239-cb8644abe993.png)

**Comment by angieskazka** [comment] 2015-11-27 11:35
duplicate of #1034

**Closed by angieskazka** 2015-11-27 11:35 UTC
Labels: comp: bubblemap, type: enhancement
