### ISSUE TITLE
Unexpected promise hell & adding buttons when changing bubble size at the first time

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#136] opened 2015-05-31 14:41 UTC
Open bubble chart on branch feature/restructure_vizabi.
1. Press "size", try to shift the slider. You will see the bubble chart turn white for a second, it's ugly (and may point out some internal bug that we are not aware of)
2. Shift the "size" slider again, all is fine now

Profile for 1: expected changing of size to the left and massive unexpected hell to the right. Why doing _addButtons and colorPicker here? Did some old promise fired suddenly?

![image](https://cloud.githubusercontent.com/assets/3648190/7902206/76c9c06e-07b1-11e5-94be-ede8120ac64b.png)

Profile of 2: expected redrawDataPoints, as normal

![image](https://cloud.githubusercontent.com/assets/3648190/7902256/be3387e4-07b3-11e5-8da5-7356dcb6ed1c.png)

**Comment by arthurcamara1** [comment] 2015-05-31 22:10
Thnx, I'll look into it :)

**Comment by arthurcamara1** [comment] 2015-06-01 13:57
Figured out what happened. There are two very distinct problems and no promise hell, but data loading instead.

*Problem 1*: buttonList was (re)adding whenever its model was ready. That meant that whenever new data was loaded, the buttons were being rendered again. That's why `addButtons` was there. This was solved by ecfeb2a8734a998424d51d07188ee76cde0f3b11 moving the button rendering to `readyOnce`

*Problem 2*: Data is being loaded again when trying to change the size (that explains the presence of promises and the while screen, which is quickly added for spinner). The reason why it tries to load new data is that we are trying to load 1952 when only 1990 is available in the response. Vizabi is smart enough to adjust that, but data caching is not. It doesn't understand that 1990-2012 is within the 1952-2012 data previously queried. Therefore, it assumes data for 1990-2012 is not present and that we need to query again. You can notice the problem is solved when we change to a correct time range. c37edadc0b7852a87a56b620244db9c8e24491c6 

So, I'm closing this issue since these problems are solved and adding #140 for the real problem with a more descriptive title and details.

**Closed by arthurcamara1** 2015-06-01 13:57 UTC
Labels: bug, help wanted
