### ISSUE TITLE
Irrelevant values are appearing on the color drop down box

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1427] opened 2016-03-09 05:11 UTC
**SEVERITY:**  Major

**MODULE:**  Pop by age chart

**Platform:**  Windows 7 / Chrome 48.0 

**RELEASE:** v0.12.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.8/preview/popbyage.html 
2)	Pop by age Chart will be loaded.
3)	Click color icon on the chart
4)	Note that irrelevant values are appearing on the color drop down box

**ACTUAL RESULTS:**
Irrelevant values are appearing on the color drop down box 

**EXPECTED RESULTS:**
Relevant values should be appeared on the color drop down box like constant etc

**SCREENSHOT:**

![v0 12 8_16](https://cloud.githubusercontent.com/assets/9950837/13625987/5058f9a6-e5df-11e5-937d-514d21a7eb44.png)

**Comment by angieskazka** [comment] 2016-03-09 09:15
closing as duplicate of #1003

**Closed by angieskazka** 2016-03-09 09:15 UTC
