### ISSUE TITLE
v0.8.3_11: Scroll bar is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#711] opened 2015-10-19 11:48 UTC
**SEVERITY:** Minor

**MODULE:** Mountain Chart

**Platform:**  iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/mountainchart.html
2)	Mountain chart page will be loaded
3)	Tap “Stack”
4)	Note that scroll bar is missing under “Manual sorting of groups”

**ACTUAL RESULTS:**
Scroll bar is missing under “Manual sorting of groups”

**EXPECTED RESULTS:** 
Scroll bar should be there under “Manual sorting of groups”

**SCREENSHOT:**

![v0 8 3_11](https://cloud.githubusercontent.com/assets/9950837/10577037/3a180ef2-7681-11e5-9551-7b37e787c9d0.PNG)

**Comment by angieskazka** [comment] 2015-10-19 11:52
closing ad duplicate of #640

**Closed by angieskazka** 2015-10-19 11:52 UTC
