### ISSUE TITLE
URL persistency

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1335] opened 2016-02-11 06:31 UTC
# Description 
URL persistency: set time slider to some point, refresh, timeslider should keep the point you gave it, and chart should load at the state of that point.
URL persistency: select a few entities, refresh, entities should be selected.

# Actual result 
**SUMMARY:**  URL link fails: Chart remains fine but URL changes

**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  iPad Air 2 iOS(9.2.1) / Safari 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Select a Country
4)	Tap Play
5)	Drag the slider to the center of slide bar
6)	Copy the URL and paste it in another tab
7)	Note that Chart remains fine but URL changes 

**ACTUAL RESULTS:**
Chart remains fine but URL changes on refreshing the page. 

**EXPECTED RESULTS:**
Changes should remain saved even after refreshing the page

# Other information 
Reported by: Abid Ali 

Test configuration: Safari 9, iPad Air 2 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/192615?tab=2&run_section_id=168039&executed_case_id=9321183#executed_case_9321183](https://valorsoftware.testlodge.com/projects/15827/runs/192615?tab=2&run_section_id=168039&executed_case_id=9321183#executed_case_9321183)

**Comment by k6Labz** [comment] 2016-02-11 07:17
Clocing as duplicate of #1332

**Closed by k6Labz** 2016-02-11 07:17 UTC
Labels: type: bug
