### ISSUE TITLE
v0.8.8_24: Bubbles and curves are not selectable by clicking

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#986] opened 2015-11-19 06:57 UTC
**SUMMARY:**
**1)** Bubbles and curves are not selectable by clicking
**2)** Hovering effect is missing

**SEVERITY:**  Critical

**MODULE:**
* Mountain chart
* Bubble chart

**Platform:**  Windows 7 / Chrome 48.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Take mouse pointer to the curves of the countries
4)	Note that hovering effect is missing and country name is not available
5)	Click to select the curve
6)	Note that curve is not selectable

**ACTUAL RESULTS:**
Curves and bubbles are not selectable by click and hovering effect is also missing. But countries can be selected by “Find” option

**EXPECTED RESULTS:**
Bubbles and curves should be selectable by click

**SCREENSHOT:**

![v0 8 8_24 1](https://cloud.githubusercontent.com/assets/9950837/11264324/92bf42d2-8eb4-11e5-87ff-a2715fa4f0e1.png)

![v0 8 8_24 2](https://cloud.githubusercontent.com/assets/9950837/11264323/92beea58-8eb4-11e5-8844-93896f3cada4.png)

**Comment by angieskazka** [comment] 2015-11-25 23:40
closing because no one could reproduce it on the popular browsers. seems like Chrome 48 bug

**Closed by angieskazka** 2015-11-25 23:40 UTC
Labels: comp: bubble-chart, comp: mountain-chart, P0: critical, state: ready, type: bug
