### ISSUE TITLE
v0.8.4_08: Curves for countries are not shown.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#746] opened 2015-10-22 10:16 UTC
**SEVERITY:** Major

**MODULE:**  Mountain Chart

**Platform:** iPhone-5 (iOS 7.1)

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/mountainchart.html
2)	Mountain chart page will be loaded
3)	Select any country like we select China, United States, Nigeria and Russia
4)	Click play. Let the slider ball reach the end
5)	Note that at the end no curve is shown for any country other than the selected ones

**ACTUAL RESULTS:**
When slider ball reach the end, no curve is shown for any country other than the selected ones

 **EXPECTED RESULTS:** 
All curves should be shown when slider ball reach the end

**Note:** “Merge Grouped” is not selected during reproducing this bug

**SCREENSHOT:**

![v0 8 4_08](https://cloud.githubusercontent.com/assets/9950837/10662698/cdce1f60-78cf-11e5-8664-9ca578bb038b.PNG)

**Comment by angieskazka** [comment] 2015-10-22 16:38
i believe this is a duplicate of #714, #684
i fixed the issue recently, it should pass on develop

**Closed by angieskazka** 2015-10-22 16:38 UTC
Labels: bug, mountain-chart
