### ISSUE TITLE
BLC_04: X-Axis & Y-Axis labels are missing in Axes menu

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#209] opened 2015-07-10 10:34 UTC
SEVERITY: Major

MODULES: Bubble Chart, Bar Chart

OS / BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2) Bubble chart page will be loaded
3) Click on Axes menu 
4) Note that x-axis & y-axis labels are missing

ACTUAL RESULTS:
X-axis & y-axis labels are missing in Axes menu

EXPECTED RESULTS: 
Both axes should be labelled as x-axis & y-axis to avoid confusion

SCREENSHOTS:
![vizabi_bubblechart_07](https://cloud.githubusercontent.com/assets/1772649/8617011/1b1b3946-2719-11e5-99d8-73c1eb0de9af.png)
![vizabi_barchart_07](https://cloud.githubusercontent.com/assets/1772649/8673225/3918e0c8-2a4e-11e5-9cf9-3548fd86f350.png)

**Comment by IncoCode** [comment] 2015-07-31 10:47
Can't reproduce this issue on `develop` branch.
![blc_04](https://cloud.githubusercontent.com/assets/6574672/9005882/996e0482-378a-11e5-9fcd-04dbf037a8ad.png)

**Comment by k6Labz** [comment] 2015-08-13 07:30
@IncoCode 
According to your screenshot attached in your above comment. This issue is fixed now as you can see about issue "summary". As now x-axis & y-axis labels are there under "Axes"

**Comment by angieskazka** [comment] 2015-08-23 11:02
This was indeed fixed in Vizabi v0.6

**Closed by angieskazka** 2015-08-23 11:02 UTC
Labels: bar-chart, bubble-chart, bug
