### ISSUE TITLE
v0.9.2_12: Stacking selector is broken //The percentage of extreme poverty is not 11.5 ± 0.3%

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1154] opened 2015-12-18 05:37 UTC
**SEVERITY:** Major

**MODULE:** Tool Page

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/mountain 
2)	Tools page is loaded.
3)	Click “Stack”, small pop up screen is displayed
4)	Click “Regions” in the first line
5)	Note that the percentage of people living in the extreme poverty is not 11.5 ± 0.3%

**ACTUAL RESULTS:**
The percentage of people living in the extreme poverty is not 11.5 ± 0.3%

**EXPECTED RESULTS:** 
The percentage of people living in the extreme poverty should be 11.5 ± 0.3%

**SCREENSHOT:**

![v0 9 2_12](https://cloud.githubusercontent.com/assets/9950837/11890173/4e82573c-a573-11e5-97d3-ef28be5d46a7.png)

**Comment by angieskazka** [comment] 2015-12-28 20:33
#1180 might be a root cause

**Comment by jheeffer** [comment] 2015-12-29 00:45
Fixed with https://github.com/Gapminder/vizabi/commit/3085685cbe2a98454c7c1bac92a6187740bbf369

**Closed by jheeffer** 2015-12-29 00:45 UTC
Labels: comp: mountain-chart, dec 23 release, P0: critical, type: bug
